#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/config/functions"
source "$PLUGIN_AVAILABLE_PATH/proxy/functions"
source "$PLUGIN_AVAILABLE_PATH/nginx-vhosts/functions"

nginx-vhost-trustproxy-disable-cmd() {
  declare desc="Disables nginx-vhost-trustproxy"
  local cmd="nginx-vhost-trustproxy:disable"

  # Support --app/$DOKKU_APP_NAME flag
  # Use the following lines to reorder args into "$cmd $DOKKU_APP_NAME $@""
  local argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  [[ -n $DOKKU_APP_NAME ]] && set -- $DOKKU_APP_NAME $@
  set -- $cmd $@
  ##

  [[ -z $2 ]] && dokku_log_fail "Please specify an app to run the command on"
  verify_app_name "$2"
  local APP="$2";

  if [[ "$(config_get $APP NGINX_VHOST_TRUSTPROXY)" != "" ]]; then
    config_unset $APP NGINX_VHOST_TRUSTPROXY
    nginx_build_config $APP
  fi
}

nginx-vhost-trustproxy-disable-cmd "$@"
