#!/usr/bin/env bash
source "$PLUGIN_AVAILABLE_PATH/nginx-vhost-trustproxy/internal-functions"
[[ " $(nginx-vhost-trustproxy-plugin-name):enable " == *" $1 "* ]] || exit "$DOKKU_NOT_IMPLEMENTED_EXIT"

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/config/functions"
source "$PLUGIN_AVAILABLE_PATH/proxy/functions"
source "$PLUGIN_AVAILABLE_PATH/nginx-vhosts/functions"

nginx-vhost-trustproxy-enable-cmd() {
  declare desc="Enables nginx-vhost-trustproxy"
  local cmd="nginx-vhost-trustproxy:enable"

  # Support --app/$DOKKU_APP_NAME flag
  # Use the following lines to reorder args into "$cmd $DOKKU_APP_NAME $@""
  local argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  [[ -n $DOKKU_APP_NAME ]] && set -- $DOKKU_APP_NAME $@
  set -- $cmd $@
  ##

  [[ -z $2 ]] && dokku_log_fail "Please specify an app to run the command on"
  verify_app_name "$2"
  local APP="$2";

  depth=${3:-1}

  if ! [[ $depth =~ ^[1-9]+$ ]]; then
    dokku_log_fail "Depth must be a positive integer for app ($APP)."
    return
  fi

  if [[ "$(is_app_proxy_enabled "$APP")" == "true" ]]; then
    config_set $APP NGINX_VHOST_TRUSTPROXY=${expr ${depth} + 1}
    nginx_build_config $APP
  else
    dokku_log_info1 "can not enable nginx-vhost-trustproxy as nginx support is disabled for app ($APP)."
  fi
}

nginx-vhost-trustproxy-enable-cmd "$@"
